#!/usr/bin/env bash
# Fetch the pinned build/test toolchain into $TOOLS_DIR (default ./tools) and
# write $TOOLS_DIR/tool-env.sh. Nothing is vendored; every download is pinned
# by version and checked against tools-src/toolchain.sha256.
#
#   bash scripts/bootstrap_tools.sh            # fetch + verify
#   UPDATE_SHA=1 bash scripts/bootstrap_tools.sh   # re-pin checksums (maintainers)
#
# JDK: uses $JAVA_HOME or java on PATH (17+ tested; CI uses Temurin 21).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TOOLS="${TOOLS_DIR:-$ROOT/tools}"
mkdir -p "$TOOLS"; TOOLS="$(cd "$TOOLS" && pwd)"
SUMS="$ROOT/tools-src/toolchain.sha256"
M=https://repo1.maven.org/maven2
G=https://dl.google.com/android/maven2

JARS=(
  "$M/org/smali/smali/2.5.2/smali-2.5.2.jar"
  "$M/org/smali/baksmali/2.5.2/baksmali-2.5.2.jar"
  "$M/org/smali/dexlib2/2.5.2/dexlib2-2.5.2.jar"
  "$M/org/smali/util/2.5.2/util-2.5.2.jar"
  "$M/org/antlr/antlr/3.5.2/antlr-3.5.2.jar"
  "$M/org/antlr/antlr-runtime/3.5.2/antlr-runtime-3.5.2.jar"
  "$M/org/antlr/stringtemplate/3.2.1/stringtemplate-3.2.1.jar"
  "$M/antlr/antlr/2.7.7/antlr-2.7.7.jar"
  "$M/com/beust/jcommander/1.64/jcommander-1.64.jar"
  "$M/com/google/guava/guava/27.1-android/guava-27.1-android.jar"
  "$M/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar"
  "$M/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar"
  "$G/com/android/tools/r8/8.3.37/r8-8.3.37.jar"
  "$G/com/android/tools/build/apksig/8.3.0/apksig-8.3.0.jar"
  "$G/com/android/tools/build/aapt2/8.3.0-10880808/aapt2-8.3.0-10880808-linux.jar"
  "$M/com/google/android/android/4.1.1.4/android-4.1.1.4.jar"
)

cd "$TOOLS"
for u in "${JARS[@]}"; do
  f="$(basename "$u")"
  [ -s "$f" ] || curl -fsSL --retry 3 -o "$f" "$u"
done

if [ "${UPDATE_SHA:-0}" = 1 ]; then
  for u in "${JARS[@]}"; do sha256sum "$(basename "$u")"; done > "$SUMS"
  echo "re-pinned $SUMS"
else
  sha256sum -c --quiet "$SUMS"
fi

# Stable names the scripts expect.
ln -sf android-4.1.1.4.jar android.jar
rm -rf aapt2-extract; mkdir aapt2-extract
(cd aapt2-extract && unzip -q ../aapt2-8.3.0-10880808-linux.jar aapt2 && chmod +x aapt2)
printf '%s' "smali-2.5.2.jar:baksmali-2.5.2.jar:dexlib2-2.5.2.jar:util-2.5.2.jar:antlr-3.5.2.jar:antlr-runtime-3.5.2.jar:stringtemplate-3.2.1.jar:antlr-2.7.7.jar:jcommander-1.64.jar:guava-27.1-android.jar:failureaccess-1.0.1.jar:jsr305-3.0.2.jar" > smali.cp

# Minimal v1+v2 signer/verifier used by the fixture build and verify_apk.sh.
rm -rf classes; mkdir classes
javac -d classes -cp apksig-8.3.0.jar "$ROOT/tools-src/MiniApkSigner.java"

cat > tool-env.sh <<ENV
# generated by scripts/bootstrap_tools.sh
export TOOLS_DIR="$TOOLS"
export SMALI_CP="\$(sed "s|^|$TOOLS/|;s|:|:$TOOLS/|g" "$TOOLS/smali.cp")"
ENV
echo "toolchain ready in $TOOLS"
